name: AzureLoginSample

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # - run: |
      #     az webapp list --query "[?state=='Running']"
      # - name: Deploy to Azure Web App
      #   run: |
      #     az webapp up --name wep-integration --resource-group wep-integration_group --sku FREE --html
      
      # - name: Set Azure subscription
      #   uses: azure/webapps-deploy@v2
      #   with:
      #     app-name: wep-integration
      #     package: .
      #     slot-name: 'production'
      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for Github integrations (i.e. PR comments)
          action: "upload"
          app_location: "src" # App source code path
          skip_app_build: true
      - name: Logout of Azure
        run: az logout
