name: AzureLoginSample

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # - run: |
      #     az webapp list --query "[?state=='Running']"
      # - name: Deploy to Azure Web App
      #   run: |
      #     az webapp up --name GithubActionsApp --runtime node
      - name: Set Azure subscription
        uses: azure/webapps-deploy@v2
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          package: src
          slot-name: 'production'
      - name: Logout of Azure
        run: az logout
