name: AzureLoginSample

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # - run: |
      #     az webapp list --query "[?state=='Running']"
      - name: Deploy to Azure Web App
        run: |
          az webapp up --name GithubActionsApp --sku FREE --html
