name: AzureLoginSample

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # - run: |
      #     az webapp list --query "[?state=='Running']"
      - name: Deploy to Azure Web App
        run: |
          az webapp up --name GithubActionsApp --resource-group StaticWebAppResourceGroup
      # - name: Set Azure subscription
      #   uses: azure/webapps-deploy@v2
      #   with:
      #     app-name: wep-integration
      #     package: .
      #     slot-name: 'production'
      # - name: Logout of Azure
      #   run: az logout
