
# File: .github/workflows/workflow.yml

on:
  push

name: AzureLoginSample

jobs:

  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Login to Azure
      uses: Azure/login@v1
      env:
        CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}
      with:
        creds: $CREDENTIALS
    

